# Generated by Django 3.1 on 2021-07-30 11:35

from django.db import migrations, models
import django.db.models.deletion
import electeez_sites.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.site')),
                ('contact_email', models.EmailField(default='contact@electis.app', max_length=254)),
                ('sender_email', models.EmailField(default='contact@electis.app', max_length=254)),
                ('all_users_can_create', models.BooleanField(default=True)),
                ('all_results_are_visible', models.BooleanField(default=True)),
            ],
            bases=('sites.site',),
            managers=[
                ('objects', electeez_sites.models.SiteManager()),
            ],
        ),
    ]
