# Generated by Django 3.2.7 on 2021-09-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electeez_sites', '0002_site_footer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='email_banner',
            field=models.ImageField(blank=True, null=True, upload_to='public/electis/images'),
        ),
        migrations.AddField(
            model_name='site',
            name='email_banner_bg',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='site',
            name='email_banner_fg',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='site',
            name='email_footer',
            field=models.ImageField(blank=True, null=True, upload_to='public/electis/images'),
        ),
        migrations.AddField(
            model_name='site',
            name='email_footer_bg',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='site',
            name='email_footer_fg',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
