# Generated by Django 3.2.7 on 2021-09-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electeez_sites', '0003_auto_20210921_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='email_banner_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='email_footer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
