# Generated by Django 3.1 on 2021-07-30 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('val', models.CharField(blank=True, max_length=5096, null=True)),
                ('nval', models.CharField(blank=True, max_length=5096, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djlang.language')),
            ],
        ),
    ]
