# Generated by Django 3.1 on 2021-08-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djlang', '0002_language_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='key',
            field=models.CharField(max_length=1024),
        ),
    ]
