# Generated by Django 3.1 on 2021-08-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djlang', '0003_auto_20210804_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='nval',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='val',
            field=models.TextField(blank=True, null=True),
        ),
    ]
