# Generated by Django 3.1.4 on 2020-12-08 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='school', max_length=100)),
                ('number_elected', models.IntegerField(default=1)),
                ('votes_allowed', models.IntegerField(default=1)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('state', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], db_index=True, default='planned', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djelectionguard.contest')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted', models.TextField(blank=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djelectionguard.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
