# Generated by Django 3.1.4 on 2020-12-15 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voters_emails', models.TextField(help_text='The list of allowed voters with one email per line')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='school', max_length=100)),
                ('number_elected', models.IntegerField(default=1)),
                ('votes_allowed', models.IntegerField(default=1)),
                ('number_guardians', models.IntegerField(default=1, verbose_name='number of guardians')),
                ('quorum', models.IntegerField(default=1, verbose_name='quorum')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('joint_public_key', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('metadata', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('context', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('device', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('store', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('plaintext_tally', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('ciphertext_tally', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('coefficient_validation_sets', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('mediator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('casted', models.DateTimeField(null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djelectionguard.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('downloaded', models.DateTimeField(null=True)),
                ('verified', models.DateTimeField(null=True)),
                ('erased', models.DateTimeField(null=True)),
                ('uploaded', models.DateTimeField(null=True)),
                ('uploaded_erased', models.DateTimeField(null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djelectionguard.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('score', models.IntegerField(null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djelectionguard.contest')),
            ],
            options={
                'ordering': ['-score', 'name'],
            },
        ),
    ]
