# Generated by Django 3.1.4 on 2020-12-16 16:17

from django.db import migrations, models
import djelectionguard.models


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0002_unique_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='number_elected',
            field=models.PositiveIntegerField(default=1, validators=[djelectionguard.models.above_0]),
        ),
        migrations.AlterField(
            model_name='contest',
            name='votes_allowed',
            field=models.PositiveIntegerField(default=1, validators=[djelectionguard.models.above_0]),
        ),
    ]
