# Generated by Django 3.1.6 on 2021-02-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0004_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='artifacts_ipfs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='artifacts_sha1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
