# Generated by Django 3.1.4 on 2021-02-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0005_artifacts_and_ipfs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='voters_emails',
        ),
    ]
