# Generated by Django 3.1.7 on 2021-02-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0006_add_decentralized'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='publish_status',
            field=models.IntegerField(default=0),
        ),
    ]
