# Generated by Django 3.1.7 on 2021-02-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0007_contest_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='decentralized',
            field=models.BooleanField(default=False),
        ),
    ]
