# Generated by Django 3.1.7 on 2021-03-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0009_decentralized_default_false'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='number_guardians',
        ),
    ]
