# Generated by Django 3.1.7 on 2021-03-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0010_auto_20210308_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
