# Generated by Django 3.1.4 on 2021-03-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0011_auto_20210308_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='close_email_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='open_email_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='guardian',
            unique_together=set(),
        ),
    ]
