# Generated by Django 3.1.7 on 2021-03-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0013_remove_contest_number_elected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='publish_status',
        ),
    ]
