# Generated by Django 3.1.7 on 2021-04-06 14:45

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0015_add_contest_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='decentralized',
        ),
    ]
