# Generated by Django 3.1.7 on 2021-04-14 11:58

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0018_random_picture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='about',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
