# Generated by Django 3.1.7 on 2021-04-16 11:15

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0019_add_field_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='about',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
