# Generated by Django 3.1.7 on 2021-05-18 06:47

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0021_candidate_description_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='previous_tracking_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='tracking_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
