# Generated by Django 3.2 on 2021-05-17 12:30

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0021_candidate_description_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='actual_start',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
