# Generated by Django 3.1 on 2021-06-16 11:40

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0022_index_actual_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='ballot_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
