# Generated by Django 3.1 on 2021-07-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0023_plaintext_spoiled_ballots'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='subtext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
