# Generated by Django 3.1 on 2021-07-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0024_candidate_subtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
