# Generated by Django 3.1 on 2021-08-11 12:52

from django.db import migrations, models


def casted_to_boolean(apps, schema_editor):
    Voter = apps.get_model('djelectionguard', 'Voter')
    Voter.objects.exclude(casted=None).update(casted_bool=True)


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0025_auto_20210706_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='casted_bool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RunPython(casted_to_boolean),
        migrations.RemoveField(
            model_name='voter',
            name='casted'
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='casted_bool',
            new_name='casted'
        )
    ]
