# Generated by Django 3.1 on 2021-08-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0026_voter_casted_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='ballot_sha1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
