# Generated by Django 3.1 on 2021-09-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djelectionguard', '0027_voter_ballot_sha1'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='decrypting',
            field=models.BooleanField(default=False),
        ),
    ]
