# Generated by Django 3.1.7 on 2021-03-29 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import electeez_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('electeez_auth', '0002_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_token',
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=electeez_auth.models.default_token, max_length=255, null=True)),
                ('expiry', models.DateTimeField(blank=True, default=electeez_auth.models.default_expiry, null=True)),
                ('redirect', models.CharField(blank=True, max_length=200, null=True)),
                ('used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
