# Generated by Django 3.1.4 on 2021-02-01 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djtezos', '0001_initial'),
        ('djelectionguard', '0004_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionContract',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djtezos.transaction')),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djelectionguard.contest')),
            ],
            bases=('djtezos.transaction',),
        ),
    ]
